### ISSUE TITLE
[PE-D] App Logo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-3/tp#139]
Maybe it would be good to add an app logo? It would look nice on the User Guide and Landing Page/README also. I'm not sure if the logo displayed in-app

![Screenshot 2021-10-29 at 5.09.25 PM.png](https://raw.githubusercontent.com/feliciaivane/ped/main/files/6bfa1e66-7e98-44bd-9958-221a01c50eb3.png)

 is the intended logo since it's the same as AB3 :") 
(Can just take a random contact book icon from the internet to use as the logo XD)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: feliciaivane/ped#9

**Comment by atyhamos** [comment]
With regards to this, I've created a logo for Track-O which keeps in line with the app's theming.

![Track-O logo](https://user-images.githubusercontent.com/44387213/139656280-89b8cb31-4e1a-497d-ac62-8c371245635e.png)

**Comment by nhjryan** [comment]
I like this logo! Very minimalist and aesthetically pleasing! :heart_eyes:
