### ISSUE TITLE
[PE-D] Command syntax might be too long for advanced users

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-3/tp#144]
![image.png](https://raw.githubusercontent.com/tenebrius1/ped/main/files/6f4c3abf-aff0-4fd0-98b7-0aa8f4679eb7.png)

Since some of your commands require users to type things like `subject` or `receive`, it might be a bit annoying to advanced users who might want shorter commands to be more efficient. 

Not sure whether yall can still add in aliases for 1.4 but its a suggestion for the future!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: tenebrius1/ped#12

**Comment by nhjryan** [comment]
Thanks for your suggestion of using aliases! I have tested some other tPs which use aliases and found it very helpful. Unfortunately, I don't think we can implement aliases in v1.4 and would take your suggestion into account should we decide to further work on this project. :)
