### ISSUE TITLE
[PE-D] Ui does not cater to long names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-3/tp#148]
![image.png](https://raw.githubusercontent.com/tenebrius1/ped/main/files/1b41f1af-95d5-4f2e-80b7-bed235977f99.png)

When a user enters a very long name, the Ui cuts it off with ellipses. Maybe you all can implement some sort of limit to your app to prevent it?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tenebrius1/ped#14

**Comment by nhjryan** [comment]
Our group consensus is that this using ellipses the correct way to deal with long names and that implementing a limit to the length of a name would be more controversial and would most probably be considered a bug as well because names in real life do not have limits as well. Hope this helps! :)
